// Code generated by rpc client generator. DO NOT EDIT.

package test

import (
	"fmt"
	"net/rpc"
)

var _ Service = (*ServiceClient)(nil)

type ServiceClient struct {
	client *rpc.Client
}

func NewServiceClient(address string) (*ServiceClient, error) {
	client, err := rpc.Dial("tcp", address)
	if err != nil {
		return nil, fmt.Errorf("test.NewServiceClient rpc.Dial error: %w", err)
	}

	return &ServiceClient{client: client}, nil
}

func (c *ServiceClient) Hello(request *Args, response *Reply) error {
	err := c.client.Call("Service.Hello", request, response)
	if err != nil {
		return fmt.Errorf("test.ServiceClient.Hello Call error: %w", err)
	}

	return nil
}

func (c *ServiceClient) Close() error {
	return c.client.Close()
}
